### ISSUE TITLE
Deixar o repositório privado, se possível

### ISSUE THREAD

**Issue by soloalex1** [codijr/modelpro#1]
Se a ideia original era produzir um sistema escalável **e que pudesse ser licenciado** para outras EJs, o ideal seria manter o repositório privado, pelo menos durante o desenvolvimento.

**Comment by mathocosta** [comment]
Entendo o teu ponto. Só que pra isso é preciso fazer o upgrade da conta de organização da container ¯\_(ツ)_/¯

**Comment by soloalex1** [comment]
F
